services:
  my-gaming-station-frontend:
    build: ./frontend/my-gaming-station-frontend
    ports:
      - "3000:3000"
    environment:
      BROWSER: "none"
    depends_on:
      - my-gaming-station-backend

  my-gaming-station-backend:
    build: ./backend/my-gaming-station-backend
    ports:
      - "1337:1337"
    environment:
      BROWSER: "none"
      SHELL: "/bin/bash"
      DATABASE_CLIENT: "mysql2"
      DATABASE_HOST: "my-gaming-station-database"  # Nombre del servicio de SQL Server
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
      AZURE_STORAGE_URL: ${AZURE_STORAGE_URL}
    depends_on:
      - my-gaming-station-database
      - my-gaming-station-storage

  my-gaming-station-database:
    image: mysql:8.0
    container_name: my-gaming-station-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  
  my-gaming-station-storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    container_name: my-gaming-station-storage
    ports:
      - "10000:10000"  # Puerto para Blob Storage
      - "10001:10001"  # Puerto para Queue Storage
      - "10002:10002"  # Puerto para Table Storage
    environment:
      AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
    command: "azurite --skipApiVersionCheck -d debug.log --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"