# Usa una imagen base de Node.js
FROM node:22.11.0

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Configurar npm para usar bash en lugar de PowerShell
RUN npm config set script-shell /bin/bash

# Copia los archivos necesarios y las dependencias
COPY package.json ./
RUN npm install

# Copia el código fuente
COPY . .

RUN mkdir -p /mnt/c/Windows/System32/WindowsPowerShell/v1.0 \
    && touch /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe \
    && chmod +x /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe

# Exponer el puerto del backend
EXPOSE 1337

# Comando para iniciar Strapi
CMD ["npm", "run", "develop"]